spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    spring.jpa.defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:test
  sql:
    init:
      #schema-locations: classpath*:db/h2/schema.sql
      data-locations: classpath*:db/h2/data.sql

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

mail:
  address:
    admin: admin@gmail.com
