spring:
  h2:
    console:
      enabled: true
      path: /h2
<<<<<<< HEAD
  jpa:
    spring.jpa.defer-datasource-initialization: true
=======
>>>>>>> 8633a62902a370eb079806ad37de11817554cdf0
  datasource:
    url: jdbc:h2:mem:test
  sql:
    init:
      schema-locations: classpath*:db/h2/schema.sql
<<<<<<< HEAD
=======
      data-locations: classpath*:db/h2/data.sql
logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
>>>>>>> 8633a62902a370eb079806ad37de11817554cdf0
