spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    spring.jpa.defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:test
  sql:
    init:
      schema-locations: classpath*:db/h2/schema.sql
