spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    defer-datasource-initialization: true
    database-platform: H2
    hibernate:
      ddl-auto: create-drop

    open-in-view: false

    properties:
      hibernate:
        format_sql: true
        show_sql: true

  redis:
    cache:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    driver-class-name: org.h2.Driver
  sql:
    init:
      #schema-locations: classpath*:db/h2/schema.sql
      data-locations: classpath*:db/h2/data.sql

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

mail:
  address:
    admin: admin@gmail.com
